version: "3.9"

services:
  app:
    container_name: web
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata fixtures/* &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache

  db:
    hostname: postgres
    container_name: database
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  cache:
    hostname: redis
    container_name: cache
    image: redis:6.0-alpine
    ports:
      - "6379:6379"