# Generated by Django 4.0.4 on 2022-04-22 22:18

import apps.core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=apps.core.models.user.default_username, max_length=150, unique=True),
        ),
    ]
