# Generated by Django 4.0.4 on 2022-04-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.IntegerField(max_length=5)),
                ('cost_per_night', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'rooms',
                'default_related_name': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.room')),
            ],
            options={
                'db_table': 'bookings',
                'default_related_name': 'bookings',
            },
        ),
    ]
