# Generated by Django 4.0.4 on 2022-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
