# Generated by Django 4.0.4 on 2022-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
    ]
